"""add project tags and preview fields

Revision ID: 0bf19790dfac
Revises: 33e1eb7f49d5
Create Date: 2025-12-04 23:09:48.329406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bf19790dfac"
down_revision: Union[str, Sequence[str], None] = "33e1eb7f49d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "source_type",
            sa.String(),
            nullable=False,
            server_default="kicad",
        ),
    )
    op.add_column("projects", sa.Column("thumbnail_kind", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "thumbnail_kind")
    op.drop_column("projects", "source_type")
    op.drop_column("projects", "tags")
    # ### end Alembic commands ###
